export const actionTypes = {
  SEND_AUTHORIZE_REQUEST : 'SEND_AUTHORIZE_REQUEST',

  AUTHORIZE_SUCCESS: 'AUTHORIZE_SUCCESS',
  AUTHORIZE_FAILED: 'AUTHORIZE_FAILED',

  SIGNOUT: 'SIGNOUT',

  REQUEST_SEARCH: 'REQUEST_SEARCH',
  RECEIVE_SEARCH: 'RECEIVE_SEARCH',

  REQUEST_PAGE: 'REQUEST_PAGE',
  RECEIVE_PAGE: 'RECEIVE_PAGE'
};
